### ISSUE TITLE
SwiftSyntaxParcer on Homebrew cannot be found as a dependency

### ISSUE THREAD

**Issue by n-belokopytov** [apple/swift-syntax#1065]
### Description

I believe that in this diff
https://github.com/apple/swift-syntax/compare/0.50700.0...0.50700.1
a mechanism was introduced to ship the library together, but only under certain conditions. Unfortunately, as seen here:
https://github.com/Homebrew/homebrew-core/actions/runs/3349028971/jobs/5548712516 - this doesn't work as expected and **lib_InternalSwiftSyntaxParser.dylib** still cannot be found. This issue is now blocking a release of Mockolo: https://github.com/uber/mockolo/issues/206

**Comment by ahoppen** [comment]
rdar://102213813

**Comment by hamishknight** [comment]
This is unrelated to the binary package change as that was also done for 5.6 (https://github.com/apple/swift-syntax/commit/0b6c22b97f8e9320bca62e82cdbee601cf37ad3f). This issue appears to be because SwiftPM no longer includes the toolchain's stdlib as an rpath (see https://github.com/apple/swift-syntax/pull/371 for more info). You could manually specify the rpath to the toolchain in Xcode.app to restore that behavior, but that's very brittle and you should consider bundling the dylib in the homebrew package instead. See https://github.com/Homebrew/homebrew-core/pull/111254/commits/a0c1d5acae3839d4b2bdbbd0a617605de4dc4bdd for an example on that, the two important parts are:

- Adding `lib.install ".build/release/lib_InternalSwiftSyntaxParser.dylib"` to bundle the parser dylib in an `if OS.mac?` block
- Adding `"-Xlinker", "-rpath", "-Xlinker", rpath` to the compile command to ensure the `lib` path is part of the rpath.

Once 5.8 is released, you may want to consider adopting [the SwiftParser library](https://github.com/apple/swift-syntax/blob/main/Sources/SwiftParser/README.md), which is a native Swift implementation of the parser that avoids the need to distribute a separate dylib.

**Comment by hamishknight** [comment]
Closing as there's nothing to fix on our end
