### ISSUE TITLE
swift should offer fixit for "#elif"

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1221]
### Description

Swift offers a fixit for #else if -> #elseif.

We should also offer a fixit for #elif, eg:

```
error: use of unknown directive '#elif'
                    #elif arch(arm64)
                    ^
```
---

```
error: unexpected 'if' keyword following '#else' conditional compilation directive; did you mean '#elseif'?
                    #else if arch(arm64)
                    ~~~~~~^~
                    #elseif
```

rdar://103506087

**Comment by TiagoMaiaL** [comment]
I've started investigating this issue. I've used the following code to check on the parser diagnostics:
```swift
        let sourceFile = Parser.parse(source: """
            #if arch(arm64)
            debugPrint("arm64")
            #elif arch(x86_64)
            debugPrint("x86_64")
            #endif
        """)
        
        let diagnostics = ParseDiagnosticsGenerator.diagnostics(for: sourceFile)
        print(diagnostics)
        print(diagnostics.flatMap(\.fixIts).map(\.message.message))
```

The above code prints the following:
```
[3:6: consecutive statements on a line must be separated by ';']
["insert \';\'"]
```

> Swift offers a fixit for #else if -> #elseif.

I've tried using ´#else if´ instead of ´#elseif´ in the code above, but here's the emitted diagnostic (which is different from the message in this issue):
```
[3:22: expected '{' in 'if' statement, 4:21: expected '}' to end 'if' statement]
["insert \'{\'", "insert \'}\'"]
```

@ahoppen Am I looking at the right place? Should I be looking for `fixIts` in `ParseDiagnosticsGenerator`?

Thanks in advance.

**Comment by bnbarham** [comment]
> Swift offers a fixit for #else if -> #elseif.

Is referring to the C++ parser in the Swift compiler. It outputs a useful diagnostic on a `#elseif`. This bug is about adding a similar diagnostic to this parser + also handling `elif` as the current diagnostics for these cases aren't great (as you saw).

https://github.com/apple/swift-syntax/blob/main/Sources/SwiftParser/SwiftParser.docc/FixingBugs.md talks about this a little. In this case `parsePoundIfDirective` will need to be updated to produce an unexpected node for the `#else` + `if` and then a missing node for `#elseif`. Similar for the `#elif` case, ie. an unexpected for `#elif` and then missing `#elseif`. After that you'll want to add a custom diagnostic in the diagnostics generator.

**Comment by TiagoMaiaL** [comment]
@ahoppen I think this can be finally closed, right? Thank you for the help!

**Comment by ahoppen** [comment]
Yes, thanks for your patience and seeing this Fix-It through 🙏🏽
