### ISSUE TITLE
Unexpected macro parsing

### ISSUE THREAD

**Issue by TiagoMaiaL** [apple/swift-syntax#1409]
### Issue Kind

Parse of Valid Source Produced Invalid Syntax Tree

### Source Code

```swift
struct S {
#if swift(>=2.2)
  let x: Int
#else
  // There should be no error here.
  let x: @#$()%&*)@#$(%&*
#endif
}
```

### Description

The above code is from the swift project, and can be found [here](https://github.com/apple/swift/blob/847dbcea529ff800eb52ced328584fb450744945/test/Parse/ConditionalCompilation/language_version.swift#L110).

Instead of parsing `x` as a constant declaration, with `@#$()%&*)@#$(%&*` as its type, the above code only parses `let x: @` as a `variableDecl`. The rest of the type is parsed in a wrong way, and the following `#$()` sequence is parsed as a `macroExpansionDecl`.

The following test fails:
```swift
  func testIfConfigExpr36() {
    AssertParse(
      """
      struct S {
      #if swift(>=2.2)
        let x: Int
      #else
        // There should be no error here.
        let x: @#$()%&*)@#$(%&*
      #endif
      }
      """
    )
  }
```

**Comment by ahoppen** [comment]
rdar://106732638

**Comment by ahoppen** [comment]
This behaves as expected because the parser doesn’t evaluate `#if` directives. The warnings in `if` directives will be emitted when invoking `swift-parser-cli` but will be hidden when SwiftParser is invoked from the compiler here: https://github.com/apple/swift/blob/8fa394f441e24e82e3da7d33a404ebe3ac7ea30a/lib/ASTGen/Sources/ASTGen/SourceFile.swift#L91-L96
