### ISSUE TITLE
Version of `AvailabilityVersionRestriction` shouldn't be optional

### ISSUE THREAD

**Issue by hamishknight** [apple/swift-syntax#1533]
### Description

The parser currently accepts e.g `if #available(macOS) {}`, whereas the C++ parser errors that a version is expected. We ought to match the C++ behavior.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://107987464

**Comment by CippoX** [comment]
Could you assign it to me? I was already looking into it.

**Comment by ahoppen** [comment]
This behaves as expected because you can add `-define-availability "_iOS13Aligned:macOS 10.15, iOS 13.0"` to the `swift-frontend` invocation and then `if #available(_iOS13Aligned, *)` is a valid availability query. Since we don’t know the compiler arguments when running the parser, we need to assume that `-define-availability` was specified for every argument to `#available`.

@CippoX I think I removed all TODOs for this but if you find any lingering ones, please just remove the TODO.
