### ISSUE TITLE
`FunctionParameterListSyntax` result builder init does not insert space between labels

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1934]
### Description

When using `FunctionParameterListSyntax.init()` with a result builder, trailing trivia should automagically be inserted after the non-`nil` first name of a parameter if a second name is specified. Otherwise, something like this:

```swift
FunctionParameterListSyntax {
  FunctionParameterSyntax(
    firstName: x, // assume == "x"
    secondName: y, // assume == "y"
    type: z // assume == "Z"
  )
}
```

Produces `xy: Z` when `x y: Z` is presumably intended.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://112664577

**Comment by ahoppen** [comment]
This behaves correctly. The syntax node initializers don’t add any trivia, they just construct the syntax tree. You need to run `.formatted()` on the tree to add the formatting whitespace.

**Comment by ahoppen** [comment]
I don’t agree that result builder initializers should automatically format your code for two reasons:

1. The `FunctionParameterSyntax` initializer that you are invoking definitely shouldn’t format your code because it’s a pure syntax node initializer defined in the SwiftSyntax module, which doesn’t know anything about formatting. That’s a fact that we cannot touch. Now, the result builder initializers should be natural extensions of these initializers and it would, IMO be very inconsistent if `FunctionParameterSyntax(…)`gave you `xy:z` but then you wrap it in the result builder `FunctionParameterListSytnax { … }` and suddenly a space starts showing up between `x` and `y`, which isn’t even part of the *list*.
2. We don’t know which format you want to you to format the tree. Do you want to indent with two spaces or four spaces? Do you want to define your own `BasicFormat` that adds newlines between function parameters? While there’s probably only one reasonable format here, these questions become very important once you use e.g. the `CodeBlock` initializer that takes a result builder. The only answer to this question would be that you’d need to pass a format to *every* result builder initializer and that’s would just clutter everything.

**Comment by grynspan** [comment]
So, I agree in general it shouldn't be trying to _format_ the output. But I think it _should_ be producing _syntactically correct_ output, at least when you're using the convenience paths and not the "here's every token in this node"-style initializers. If I use the latter, then yes, it's on me to do it properly. But if I'm using a result builder with a convenience initializer, and it results in bad code unless I manually take extra steps to correct it, then what was the value in using the result builder?

To be clear, I am _not_ advocating for full formatting of output, just the bare minimum required to make the result of a result builder syntactically valid.

**Comment by ahoppen** [comment]
> So, I agree in general it shouldn't be trying to _format_ the output. But I think it _should_ be producing _syntactically correct_ output, at least when you're using the convenience paths and not the "here's every token in this node"-style initializers. If I use the latter, then yes, it's on me to do it properly. But if I'm using a result builder with a convenience initializer, and it results in bad code unless I manually take extra steps to correct it, then what was the value in using the result builder?

My main concern here is that users of swift-syntax shouldn’t need to worry about which initializers are convenience initializers and which once are the dedicated initializers. The distinction between the two is a fairly arbitrary implementation detail. In the long run, the two being inconsistent wrt formatting will cause more frustration than it solves. Right now we have a simple rule: You need to format the output yourself.

> To be clear, I am _not_ advocating for full formatting of output, just the bare minimum required to make the result of a result builder syntactically valid.

That’s all that `BasicFormat` (and thus `.formatted()`) does, really: Add sufficiently much trivia to separate tokens so that it parses again. Note that to separate code block items, we also need to add newlines, so it’s not just about adding spaces. And the final piece is that we also do the basic indentation handling (no line wrapping or anything complicated) so that it’s somewhat readable.

**Comment by grynspan** [comment]
I defer to you here, ultimately. I've made my case, but if you still feel the current API is sufficient, we can close this issue.

**Comment by ahoppen** [comment]
Most of all, I feel like the current API is consistent with the other APIs and I usually strive for consistency as a main goal because it produces the least amount of surprise.
