### ISSUE TITLE
SwiftSyntax doesn't build on macOS version < 13

### ISSUE THREAD

**Issue by SimplyDanny** [apple/swift-syntax#2116]
Trying to update SwiftSyntax from [509.0.0-swift-DEVELOPMENT-SNAPSHOT-2023-07-09-a](https://github.com/apple/swift-syntax/releases/tag/509.0.0-swift-DEVELOPMENT-SNAPSHOT-2023-07-09-a) to [509.0.0-swift-DEVELOPMENT-SNAPSHOT-2023-08-07-a](https://github.com/apple/swift-syntax/releases/tag/509.0.0-swift-DEVELOPMENT-SNAPSHOT-2023-08-07-a) I faced compile errors in a macOS 12 VM. A few examples:
```
/Users/runner/work/1/s/.build/checkouts/swift-syntax/Sources/SwiftSyntax/SyntaxCollection.swift:363:53: error: cannot specialize protocol type 'Sequence'
  public static func += (lhs: inout Self, rhs: some Sequence<Element>) {
                                                    ^
/Users/runner/work/1/s/.build/checkouts/swift-syntax/Sources/SwiftSyntax/Raw/RawSyntaxLayoutView.swift:61:25: error: cannot specialize protocol type 'Collection'
    with elements: some Collection<RawSyntax?>,
                        ^
/Users/runner/work/1/s/.build/checkouts/swift-syntax/Sources/SwiftSyntax/Raw/RawSyntax.swift:823:27: error: cannot specialize protocol type 'Collection'
    from collection: some Collection<RawSyntax?>,
                          ^
/Users/runner/work/1/s/.build/checkouts/swift-syntax/Sources/SwiftSyntax/SyntaxCollection.swift:363:53: error: cannot specialize protocol type 'Sequence'
  public static func += (lhs: inout Self, rhs: some Sequence<Element>) {
                                                    ^
```
It seems that opaque types like `some Collection<Element>` and the like require a certain SDK version. In case of macOS, such a supporting SDK is only available from macOS 13. `Package.swift` specifies macOS 10.15 as a minimum. That seems to be too low if the erring opaque types are now in use in SwiftSyntax' code base.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114658666

**Comment by ahoppen** [comment]
@SimplyDanny Which version of Xcode and (if applicable) which Swift Open Source Toolchain do you have installed on the macOS 12 VM? The OS itself shouldn’t make a difference, just the SDK that’s installed in Xcode. My assumption is that you have Xcode 14.0 installed because it comes with the macOS 12 SDK but the Swift 5.7 compiler.

I agree that we might have a mismatch here that needs to be fixed. I just want to understand the issue fully before jumping to any conclusions.

**Comment by ahoppen** [comment]
The following is assuming that you are using Xcode 14.0 or 14.0.1.

This is an issue in Xcode. Xcode 14.0 contains the Swift 5.7 compiler but the macOS 12.3 SDK, which contains the Swift 5.6 standard library. Since that standard library doesn’t declare `Sequence` and `Collection` with primary associated types, they don’t compile. So, the deployment target declaration in swift-syntax is correct and the fix is that you need to update your Xcode to 14.1 or later.

**Comment by SimplyDanny** [comment]
Thank you for your fast reply and helpful hints!

Yes, indeed with Xcode 14.1 on macOS 12 it compiles.

Just to make sure my understanding is correct, as I always get a little confused by these different players involved: In oder to compile SwiftSyntax, we need at least a Swift 5.7 compiler together with a version of the Swift Standard Library that declares `Sequence` and `Collection` with primary associated types (among other features). This library is provided in the macOS SDK starting from version 13. Both come with Xcode 14.1 independent of the OS it is running on. As primary associated types don't require runtime support, the actual deployment target can be lower than the SDK version. Xcode would complain if SwiftSyntax was using an API that's unavailable on any of the supported deployment targets.

The minimum deployment target is specified in Package.swift. But how does one know which Swift and SDK version is required to build a package successfully?

**Comment by ahoppen** [comment]
> Just to make sure my understanding is correct…

Everything correct

> The minimum deployment target is specified in Package.swift. But how does one know which Swift and SDK version is required to build a package successfully?

That’s what we use the `swift-tools-version` in the package manifest for. If your Swift is older than that version, swift-syntax won’t compile. The only catch here is that this checks the compiler version, not the stdlib version and Xcode 14 is a weirdo in that regard because it contains a different stdlib version in the macOS SDK than the compiler it ships with.

**Comment by SimplyDanny** [comment]
> > The minimum deployment target is specified in Package.swift. But how does one know which Swift and SDK version is required to build a package successfully?
> 
> That’s what we use the `swift-tools-version` in the package manifest for. If your Swift is older than that version, swift-syntax won’t compile. The only catch here is that this checks the compiler version, not the stdlib version and Xcode 14 is a weirdo in that regard because it contains a different stdlib version in the macOS SDK than the compiler it ships with.

I see. Normally, the compiler comes with a matching standard library. With the mismatch in Xcode 14, I just trapped into an exceptional case.

Sorry, if this was a bit off-topic. Closing the issue. Thanks @ahoppen!

**Comment by ahoppen** [comment]
No problem at all. I was happy to explain it. And thanks for raising the issue. It might have been something more serious.
