### ISSUE TITLE
Missing required module '_AtomicBool'

### ISSUE THREAD

**Issue by HassanTaleb90** [apple/swift-syntax#2610]
### Steps to Reproduce

Version used: main
Code: `import SwiftSyntax`

<img width="1016" alt="Screenshot 2024-04-20 at 11 28 29 AM" src="https://github.com/apple/swift-syntax/assets/49780321/7f0bd188-caf3-4b45-9b25-651867628f08">

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://126796103

**Comment by ahoppen** [comment]
I think it might be a missing dependency declaration on your side because I have never seen this issue before. Could you double-check that you declared a dependency from the target that you’re seeing this issue in to `SwiftSyntax` (or any other target in the `swift-syntax` package) as follows

```swift
.product(name: "<…>", package: "swift-syntax")
```

If that’s not the problem, could you share the project that you’re seeing the issue in. If that’s not possible and it’s a SwiftPM project, could you share `Package.swift` and the name of the target that you are seeing this issue in?
