### ISSUE TITLE
Round-trip failure with @specialize attribute

### ISSUE THREAD

**Issue by DougGregor** [apple/swift-syntax#679]
### Issue Kind

Round-Trip Failure

### Source Code

```swift
@_specialize(e
```

**Comment by ahoppen** [comment]
rdar://99430626

**Comment by MEnnabah** [comment]
This fails a check of the specialized attribute argument (`e` in this case). 

[`parseSpecializeAttributeSpecList()`][parseSpecializeAttributeSpecList] checks whether the argument is a valid specialized parameter[^1], or a `where` clause. Otherwise, it [`fatalError()`][fatalError].

I think in this case, we should return a representation of the invalid argument. If this is true, I'm not sure which type to use. But I think we have `RawUnknown..` types. Would you please guide me what is a valid type here?


[^1]: Valid parameters are `target`, `availability`, `exported`, `kind`, `spi`, `spiModule`, or `available`.

[parseSpecializeAttributeSpecList]: https://github.com/apple/swift-syntax/blob/main/Sources/SwiftParser/Attributes.swift#L491
[fatalError]: https://github.com/apple/swift-syntax/blob/main/Sources/SwiftParser/Attributes.swift#L497

**Comment by ahoppen** [comment]
I think adding `RawUnknownNodesSyntax` to `elements` would be the correct solution here.

**Comment by MEnnabah** [comment]
Thanks @ahoppen! I don't think I was able to find this type (I'm on `main` branch). Would you please point me where I can find it if it's in another branch?

Note: All of the `RawUnknown..` types initializers would return `nil` because `ident.tokenKind` is `SwiftSyntax.RawTokenKind.identifier`. That probably means we need to change [`let ident = self.parseAnyIdentifier()`][ident] to return a valid type.

[ident]: https://github.com/apple/swift-syntax/blob/main/Sources/SwiftParser/Attributes.swift#L495
<img width="427" alt="Screenshot 2022-09-05 at 12 42 34" src="https://user-images.githubusercontent.com/16809714/188407277-693777aa-2765-4644-8dc8-5f1a6b3673f4.png">

**Comment by MEnnabah** [comment]
Thanks @ahoppen!

**Comment by ahoppen** [comment]
Reading this again, what I meant was `RawUnexpectedNodesSyntax`. But I think both solutions of producing `RawUnknownNodesSyntax` or `RawLabeledSpecializeEntrySyntax` are equally fine.

**Comment by MEnnabah** [comment]
I think I looked at `RawUnexpectedNodesSyntax`. However, I'm not sure if I was able to properly construct the missing tokens.

> Reading this again, what I meant was RawUnexpectedNodesSyntax. But I think both solutions of producing `RawUnknownNodesSyntax` or `RawLabeledSpecializeEntrySyntax` are equally fine.

Just to make sure I understand what you mean correctly, did you mean `RawUnexpectedNodesSyntax` instead of `RawUnknownNodesSyntax`?

**Comment by ahoppen** [comment]
> Just to make sure I understand what you mean correctly, did you mean `RawUnexpectedNodesSyntax` instead of `RawUnknownNodesSyntax`?

Yes
