### ISSUE TITLE
Still getting "Library not loaded: '@rpath/lib_InternalSwiftSyntaxParser.dylib'" error after upgrading tool to 0.50700.1

### ISSUE THREAD

**Issue by Jeehut** [apple/swift-syntax#884]
### Description

I upgraded [BartyCrouch](https://github.com/FlineDev/BartyCrouch) to the latest [swift-syntax release](https://github.com/apple/swift-syntax/releases/tag/0.50700.1) but it's still failing with `dyld[15423]: Library not loaded: '@rpath/lib_InternalSwiftSyntaxParser.dylib'` – how do we need to link it?

I followed all instructions in the release, but it doesn't work ... help would be appreciated! @ahoppen 
Either something is wrong with the release, or instructions of how to depend on SwiftSyntax properly should be updated.

### Steps to Reproduce

As you can see on my [Homebrew PR](https://github.com/Homebrew/homebrew-core/pull/112470)'s CI fail [here](https://github.com/Homebrew/homebrew-core/actions/runs/3194944345/jobs/5215094791), running my tool which includes the latest release, e.g. via `bartycrouch update` results in this error. You should be able to simply build my [BartyCrouch](https://github.com/FlineDev/BartyCrouch) app locally via `make install`, then run `/path/to/bartycrouch update` inside a folder with a `.swift` and a `.strings` file to reproduce (see also the [test function](https://github.com/FlineDev/BartyCrouch/blob/main/Formula/bartycrouch.rb#L13-L32)).

**Comment by ahoppen** [comment]
rdar://100842452

**Comment by ahoppen** [comment]
The problem is that bartycrouch links against `lib_InternalSwiftSyntaxParser.dylib` dynamically but you aren’t vendoring that library as part of `barycrouch`. If you copy `lib_InternalSwiftSyntaxParser.dylib` next to `bartycrouch`, the issue disappears. If you don’t want to put the library into a different directory (e.g. `lib` instead of `bin`), you could try adding an rpath to the binary that points to the directory that contains `lib_InternalSwiftSyntaxParser.dylib`.

You might also find https://github.com/keith/StaticInternalSwiftSyntaxParser/ interesting, which contains a static version of that parser library, maintained by @keith.

**Comment by ahoppen** [comment]
If this continues to be an issue for you, feel free to re-open the issue.

**Comment by Jeehut** [comment]
@ahoppen Thank you very much for your help. I am now trying to use the static parser provided by @keith and already made a new release with the appropriate changes. Hope it goes through this time. If not, I might ask more questions. Here's the PR: https://github.com/Homebrew/homebrew-core/pull/112557

**Comment by Jeehut** [comment]
Update: It worked, the Homebrew PR went through without problems this time. Thank you again @ahoppen!
